plugins:
  - jekyll-sitemap

url: "https://savannahferretti.github.io"

title: Savannah Ferretti
description: "Savannah Ferretti is a PhD candidate in Earth System Science at UC Irvine, researching tropical rainfall and the South Asian monsoon using statistical and machine learning models."

author:
  name: "Savannah Ferretti"
  avatar: "/files/profile.jpg"
  bio: "PhD Candidate in Earth System Science" 
  location: "Long Beach, CA"
  employer: "UC Irvine"
  email: "savannah.ferretti@uci.edu"
  googlescholar: "https://scholar.google.com/citations?user=kH2IC6wAAAAJ&hl"
  linkedin: "savannahferretti"
  github: "savannahferretti"
