title: Savannah Ferretti
description: "PhD Candidate in Earth System Science"

author:
  name: "Savannah Ferretti"
  avatar: "/files/profile.jpg"
  bio: "PhD candidate in Earth System Science, working with Mike Paritchard and Jane Baldwin. I build machine learning methods for high-dimensional biological data and am actively seeking industry research roles."
  location: "Long Beach ,CA"
  employer: "Univeristy of California, Irvine"
  email: "savannah.ferretti@uci.edu"
  googlescholar: "https://scholar.google.com/citations?user=XXXXXXXX"
  linkedin: "savannahferretti"
  github: "savannahferretti"
  cv: "/files/resume.pdf"
